// Array of images with their paths and alt descriptions
const images = [
    { src: 'image1.jpg', alt: ' Image 2 Description' },
    { src: 'image2.jpg', alt: 'Image 2 Description' },
    { src: 'image3.jpg', alt: 'Image 3 Description' },
    { src: 'image4.jpg', alt: 'Image 4 Description' },
    { src: 'image5.jpg', alt: 'Image 5 Description' },
    { src: 'image6.jpg', alt: 'Image 6 Description' },
    { src: 'image7.jpg', alt: 'Image 7 Description' },
    { src: 'image8.jpg', alt: 'Image 8 Description' },
    { src: 'image9.jpg', alt: 'Image 9 Description' },
    { src: 'image10.jpg', alt: 'Image 10 Description' },
    { src: 'image11.jpg', alt: 'Image 11 Description' },
    { src: 'image12.jpg', alt: 'Image 12 Description' },
    { src: 'image13.jpg', alt: 'Image 13 Description' },
    { src: 'image14.jpg', alt: 'Image 14 Description' },
    { src: 'image15.jpg', alt: 'Image 15 Description' },
    { src: 'image16.jpg', alt: 'Image 16 Description' },
    { src: 'image17.jpg', alt: 'Image 17 Description' },
    { src: 'image18.jpg', alt: 'Image 18 Description' },
];
